---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    jkube.eclipse.org/scm-url: https://github.com/spring-projects/spring-boot/docker-app-demo1
    jkube.eclipse.org/scm-tag: HEAD
  labels:
    app: docker-app-demo1
    provider: jkube
    version: 1.0.4
    group: com.scsb.example
  name: docker-app-demo1
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: docker-app-demo1
      provider: jkube
      group: com.scsb.example
  template:
    metadata:
      annotations:
        jkube.eclipse.org/scm-url: https://github.com/spring-projects/spring-boot/docker-app-demo1
        jkube.eclipse.org/scm-tag: HEAD
      labels:
        app: docker-app-demo1
        provider: jkube
        version: 1.0.4
        group: com.scsb.example
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: greeting.message
          value: "JKube, Hello to -"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: docker.io/charlottescsb/jkub-docker-app-demo1:1.0.4
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false
      serviceAccount: sa-docker-app-demo1
